### ISSUE TITLE
Upload error on windows 

### ISSUE THREAD

**Issue by Siedlerchr** [garygrossgarten/github-action-scp#1]
Hi,

seems like I have to open the first issue here. 
We are recently experiencing problems running the actions and uploading files from a Windows runner.
The artficacts are currently around 300 MB each
Interestingly running under linux and mac uploading the corresponding files does work without problems.
Any idea what the error could be?

Link to run: https://github.com/JabRef/jabref/runs/307971519
```
Establishing a SSH connection to builds.jabref.org.
🤝 Connected to builds.jabref.org.
Starting scp Action: build/distribution to www/master
❕copy failed for build\distribution\JabRef-portable_windows.zip.
❕copy failed for build\distribution\JabRef-5.0.0.msi.
The copy of directory build/distribution was unsuccessful.
failed transfers [object Object], [object Object]
Retrying to copy build\distribution\JabRef-portable_windows.zip to www/master/JabRef-portable_windows.zip.
⚠️ An error happened:(. Failure Error: Failure
    at SFTPStream._transform (d:\a\_actions\garygrossgarten\github-action-scp\release\node_modules\ssh2-streams\lib\sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:189:10)
    at SFTPStream._read (d:\a\_actions\garygrossgarten\github-action-scp\release\node_modules\ssh2-streams\lib\sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
    at SFTPStream.Writable.write (_stream_writable.js:301:11)
    at Channel.ondata (_stream_readable.js:713:22)
    at Channel.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
 1: 00007FF607A0814F napi_wrap+121231
 2: 00007FF6079B16F6 uv_loop_fork+44550
 3: 00007FF60795A859 v8::internal::StackGuard::ArchiveSpacePerThread+26553
 4: 00007FF607F9A049 v8::internal::OFStreamBase::xsputn+5065
 5: 00007FF607F99588 v8::internal::OFStreamBase::xsputn+2312
 6: 00007FF607F998B8 v8::internal::OFStreamBase::xsputn+3128
 7: 00007FF607F996DD v8::internal::OFStreamBase::xsputn+2653
 8: 00007FF608554196 v8::internal::NativesCollection<0>::GetScriptsSource+662454
##[error]Node run failed with exit code 134
```

**Comment by garygrossgarten** [comment]
Hi @Siedlerchr ,

thank you for submitting an issue. I currently don't know what's causing the issue. I'll try to recreate your issue and report back as soon as I have some information.

**Comment by Siedlerchr** [comment]
Hi,
I think this can be closed. It seemed like a temporary issue with either our sftp server or the windows build.
