### ISSUE TITLE
Error Copying Folder

### ISSUE THREAD

**Issue by LeBeatle** [garygrossgarten/github-action-scp#5]
Hi,
I am getting following Error copying a Folder: 

``` An error happened:(. Failure Error: Failure
    at SFTPStream._transform (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/node_modules/ssh2-streams/lib/sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:189:10)
    at SFTPStream._read (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at SFTPStream.Writable.write (_stream_writable.js:305:11)
    at Channel.ondata (_stream_readable.js:727:22)
    at Channel.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
 1: 0x9da7c0 node::Abort() [/home/runner/runners/2.163.1/externals/node12/bin/node]
 2: 0xa4e219  [/home/runner/runners/2.163.1/externals/node12/bin/node]
 3: 0xba5d59  [/home/runner/runners/2.163.1/externals/node12/bin/node]
 4: 0xba7b47 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/runner/runners/2.163.1/externals/node12/bin/node]
 5: 0x13750d9  [/home/runner/runners/2.163.1/externals/node12/bin/node]
##[error]Node run failed with exit code 134
```

My config is: 

``` name: RPI Install

 on: 
  push:
    branches:
      - master
 jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./
          remote: '/var/www/html/[folderName]/'
          host: [domainname]
          port: 22
          username: xxxxx
          password: xxxxx
```

The Authentication itself works and the first few files get copied without any Problem but after some files/folders it crashes. I have no clue why. Does anybody know what the Problem could be?

**Comment by DanielFerguson** [comment]
Having the same error

**Comment by robertnisipeanu** [comment]
Same happens to me, seems like it's because one of the file is opened on the server (in my case i have a service running that software). First stopping the service, then copying the files and then starting the service again works fine.

**Comment by stwf** [comment]
I get this problem too and it isn't an open file running. I think it's when it tries to create a folder inside a folder. Anyway this would really be a useful plugin for me, I hope this can get cleared up. Same stack trace as the other issue...
```
Starting scp Action: _build/prod/rel/***/ to apps/***/
⚠️ An error happened:(. Failure Error: Failure
    at SFTPStream._transform (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/node_modules/ssh2-streams/lib/sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:189:10)
    at SFTPStream._read (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at SFTPStream.Writable.write (_stream_writable.js:305:11)
    at Channel.ondata (_stream_readable.js:727:22)
    at Channel.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
 1: 0x9da7c0 node::Abort() [/home/runner/runners/2.164.0/externals/node12/bin/node]
 2: 0xa4e219  [/home/runner/runners/2.164.0/externals/node12/bin/node]
 3: 0xba5d59  [/home/runner/runners/2.164.0/externals/node12/bin/node]
 4: 0xba7b47 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/runner/runners/2.164.0/externals/node12/bin/node]
 5: 0x13750d9  [/home/runner/runners/2.164.0/externals/node12/bin/node]
```

**Comment by shuiRong** [comment]
> Same happens to me, seems like it's because one of the file is opened on the server (in my case i have a service running that software). First stopping the service, then copying the files and then starting the service again works fine.

Same here. I must stop the program running on the remote server and re-run Github Actions again. 
It's weird and I will find the solution.

**Comment by garygrossgarten** [comment]
@shuiRong does using the atomicPut option merged in 0.7.0 solve this issue?

**Comment by shuiRong** [comment]
> @shuiRong does using the atomicPut option merged in 0.7.0 solve this issue?

I will try later and see if it works

**Comment by shuiRong** [comment]
@garygrossgarten Yes, `atomicPut ` works. Thanks.

**Comment by garygrossgarten** [comment]
Awesome, thanks for reporting!
