### ISSUE TITLE
An error happened:(. Failure Error: Failure at SFTPStream._transform 

### ISSUE THREAD

**Issue by reime005** [garygrossgarten/github-action-scp#6]
I just got an error, trying to copy the build folder of a react (+ typescript) app.

See the following log:

2020-01-19T14:01:38.4934264Z 🤝 Connected to ***.
2020-01-19T14:01:38.4949319Z Starting scp Action: build to /var/www/html
2020-01-19T14:01:39.2311992Z ✔ successfully copied build/favicon.ico.
2020-01-19T14:01:39.2322901Z ✔ successfully copied build/index.html.
2020-01-19T14:01:39.2324479Z ✔ successfully copied build/logo192.png.
2020-01-19T14:01:39.2325096Z ✔ successfully copied build/logo512.png.
2020-01-19T14:01:39.3252087Z ✔ successfully copied build/asset-manifest.json.
2020-01-19T14:01:39.5263142Z ✔ successfully copied build/manifest.json.
2020-01-19T14:01:39.5263929Z ✔ successfully copied build/precache-manifest.5819b140bec6caa594a49d12a925d064.js.
2020-01-19T14:01:39.5268514Z ✔ successfully copied build/robots.txt.
2020-01-19T14:01:39.5268976Z ✔ successfully copied build/service-worker.js.
2020-01-19T14:01:39.8198875Z ❕copy failed for build/static/js/2.c46ada58.chunk.js.map.
2020-01-19T14:01:39.9124497Z ⚠️ An error happened:(. Failure Error: Failure
2020-01-19T14:01:39.9125179Z     at SFTPStream._transform (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/node_modules/ssh2-streams/lib/sftp.js:412:27)
2020-01-19T14:01:39.9125440Z     at SFTPStream.Transform._read (_stream_transform.js:189:10)
2020-01-19T14:01:39.9126034Z     at SFTPStream._read (/home/runner/work/_actions/garygrossgarten/github-action-scp/release/node_modules/ssh2-streams/lib/sftp.js:183:15)
2020-01-19T14:01:39.9126376Z     at SFTPStream.Transform._write (_stream_transform.js:177:12)
2020-01-19T14:01:39.9126578Z     at doWrite (_stream_writable.js:431:12)
2020-01-19T14:01:39.9126774Z     at writeOrBuffer (_stream_writable.js:415:5)
2020-01-19T14:01:39.9126991Z     at SFTPStream.Writable.write (_stream_writable.js:305:11)
2020-01-19T14:01:39.9127200Z     at Channel.ondata (_stream_readable.js:727:22)
2020-01-19T14:01:39.9127390Z     at Channel.emit (events.js:210:5)
2020-01-19T14:01:39.9127820Z     at addChunk (_stream_readable.js:309:12)
2020-01-19T14:01:40.1446462Z  1: 0x9da7c0 node::Abort() [/home/runner/runners/2.163.1/externals/node12/bin/node]
2020-01-19T14:01:40.1450787Z  2: 0xa4e219  [/home/runner/runners/2.163.1/externals/node12/bin/node]
2020-01-19T14:01:40.1456720Z  3: 0xba5d59  [/home/runner/runners/2.163.1/externals/node12/bin/node]
2020-01-19T14:01:40.1463820Z  4: 0xba7b47 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/runner/runners/2.163.1/externals/node12/bin/node]
2020-01-19T14:01:40.1472722Z  5: 0x13750d9  [/home/runner/runners/2.163.1/externals/node12/bin/node]
2020-01-19T14:01:41.6627352Z ##[error]Node run failed with exit code 134
2020-01-19T14:01:41.6639917Z Cleaning up orphan processes

**Comment by stwf** [comment]
I was getting this and realized it was happening when the second level of folder was traversed. I saw the parameter for recursive but left it in the default state of true.
But explicitly setting this to true fixed this issue for me.

**Comment by jmbockhorst** [comment]
I am running into this exact issue as well.

**Comment by deepadeshraa** [comment]
I am also facing this issue.

**Comment by BeBeBerr** [comment]
> I was getting this and realized it was happening when the second level of folder was traversed. I saw the parameter for recursive but left it in the default state of true.
> But explicitly setting this to true fixed this issue for me.

Thanks, it works for me too.

**Comment by deepadeshraa** [comment]
> > I was getting this and realized it was happening when the second level of folder was traversed. I saw the parameter for recursive but left it in the default state of true.
> > But explicitly setting this to true fixed this issue for me.
> 
> Thanks, it works for me too.

Could you please explain me what exactly you did ?

**Comment by BeBeBerr** [comment]
> > > I was getting this and realized it was happening when the second level of folder was traversed. I saw the parameter for recursive but left it in the default state of true.
> > > But explicitly setting this to true fixed this issue for me.
> > 
> > 
> > Thanks, it works for me too.
> 
> Could you please explain me what exactly you did ?

Set the parameter 'recursive' to true explicitly like this:
```
with:
  recursive: true
```

**Comment by garygrossgarten** [comment]
Closing due to inactivity. If the answer provided by @BeBeBerr doesn't work, feel free to open the issue again.
